# Site settings
title: Faith Tan
email: seventanyb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am web developer from China
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://serventanyb.com" # the base hostname & protocol for your site
twitter_username: Tanybseven
github_username:  july-12

# Build settings
markdown: kramdown
